### ISSUE TITLE
Feature - inject wallet into different namespace

### ISSUE THREAD

**Issue by marcuspuchalla** [fabianbormann/cardano-peer-connect#4]
Currently, the wallet will be injected into `window.cardano.WALLETNAME`.
This can be an issue when the same wallet is also injected differently through, e.g., a browser extension.

I suggest injecting the API into `window.cardanop2p.WALLETNAME`

This way, the DApp implementing cardano-peer-connect could let the user switch between his browser extension and peer-connected wallets.

**Comment by fabianbormann** [comment]
Even if I already merged PR #7 I would keep this discussion here open, because there is also some value of injecting the wallet to ```window.cardano``` instead of ```window.cardanop2p```. E.g. libs like the CF connect button component and other libs (from meshjs) are scanning for CIP30 compliant wallets in ```window.cardano```. This means that those libs would support cardano-peer-connect without the need of any adjustment. It would also be possible to rename the wallet to [walletname]-p2p to prevent conflicts between browser extensions and peer connections.

**Comment by marcuspuchalla** [comment]
> Even if I already merged PR #7 I would keep this discussion here open, because there would be also some value of injecting the wallet to `window.cardano` instead of `window.cardanop2p`.
> 
> E.g. libs like the CF connect button component and other libs (from meshjs) are scanning for CIP30 compliant wallets in `window.cardano`. This means that those libs would support cardano-peer-connect without the need of any adjustment. It would also be possible to rename the wallet to [walletname]-p2p to prevent conflicts between browser extensions and peer connections.

I totally agree and have already closed the PR.

So wallets should now inject into window.cardano.[walletname]-p2p

And in addition, we will implement a check here, to warn a wallet if it is injecting into an already defined namespace.

**Comment by fabianbormann** [comment]
Done by merging PR #10 🎆
